export const MATERIAL_CONSTANTS = {
    MIPMAP_BIAS_SHARP: -0.5,
    MIPMAP_BIAS_DEFAULT: 0.0,
    ENV_MAP_INTENSITY_DEFAULT: 1.0,
    ENV_MAP_INTENSITY_FLOOR: 1.5,
    ENV_MAP_INTENSITY_WALL: 1.3,
    ENV_MAP_INTENSITY_BASE: 1.2,
    ROUGHNESS_MIN: 0.05,
    ROUGHNESS_CEILING: 0.9,
    ROUGHNESS_FLOOR_PROCEDURAL: 0.8,
    ROUGHNESS_WALL_PROCEDURAL: 0.85,
    ROUGHNESS_WINDOW_FRAME: 0.3,
    ROUGHNESS_CHAIR_SEAT: 0.7,
    ROUGHNESS_TABLE_TOP: 0.6,
    METALNESS_NON_METAL: 0.0,
    METALNESS_WINDOW_FRAME: 0.1,
    METALNESS_CHAIR_LEGS: 0.8,
    NORMAL_SCALE_DEFAULT: 0.25,
    AO_INTENSITY_DEFAULT: 1.0
};

export const POSTPROCESSING_CONSTANTS = {
    BLOOM_THRESHOLD: 1.5,
    BLOOM_STRENGTH: 0.5,
    BLOOM_RADIUS: 0.6,
    VIGNETTE_OFFSET: 1.0,
    VIGNETTE_DARKNESS: 1.1,
    N8AO_SAMPLES: 8,
    N8AO_DENOISE_SAMPLES: 2,
    N8AO_DENOISE_RADIUS: 8,
    N8AO_RADIUS: 0.5,
    N8AO_DISTANCE_FALLOFF: 2.0,
    N8AO_INTENSITY: 1.5,
    BACKGROUND_BLURRINESS: 0.05
};

export const GEOMETRY_CONSTANTS = {
    FLOOR_EXTEND: 0.05,
    FLOOR_SHIFT: 0.025,
    WALL_TEXTURE_SCALE: 2,
    FLOOR_TEXTURE_SCALE: 2,
    DOOR_OPENING_REDUCE_WIDTH: 0.10,
    DOOR_OPENING_REDUCE_HEIGHT: 0.05,
    DOOR_OPENING_Y_OFFSET: -0.025,
    WINDOW_GLASS_Z_OFFSET: 0.01,
    WINDOW_FRAME_THICKNESS: 0.1,
    WINDOW_FRAME_WIDTH: 0.05
};

export const LIGHTING_CONSTANTS = {
    SUN_MOVE_BACK_DISTANCE: 2.0,
    SUN_TARGET_Y: 1.5,
    SHADOW_BIAS_DEFAULT: -0.0005,
    SHADOW_BIAS_SPOT: -0.00001,
    SHADOW_BIAS_SPOT_SIDE: -0.0000002,
    SHADOW_NORMAL_BIAS_DEFAULT: 0.015,
    SHADOW_NORMAL_BIAS_SPOT_SIDE: 0.0095,
    SHADOW_RADIUS: 3,
    SHADOW_RADIUS_SPOT: 4,
    SHADOW_CAMERA_NEAR: 0.1,
    SHADOW_CAMERA_FAR: 10,
    SHADOW_CAMERA_NEAR_SPOT: 0.0001,
    SHADOW_CAMERA_FAR_FALLBACK: 100,
    SHADOW_MAP_SIZE_DIRECTIONAL: 1024,
    SHADOW_MAP_SIZE_SPOT: 512,
    SCENE_SIZE: 5,
    SCENE_HEIGHT: 5,
    FOV_MARGIN_SMALL: 1.3,
    FOV_MARGIN_LARGE: 1.8,
    FOV_ANGLE_THRESHOLD: 30,
    FAR_MARGIN_POINT: 1.5,
    LAMP_HEIGHT_OFFSET: -0.1,
    LAMP_BULB_Y_OFFSET: 0.25
};

export const CAMERA_CONSTANTS = {
    FOV: 50,
    NEAR: 0.1,
    FAR: 100
};

export const CONTROLS_CONSTANTS = {
    DAMPING_FACTOR: 0.05,
    MIN_DISTANCE: 1,
    MAX_DISTANCE: 10,
    MAX_POLAR_ANGLE: Math.PI / 2.1,
    MIN_POLAR_ANGLE: Math.PI / 4
};

export const RENDERER_CONSTANTS = {
    TONE_MAPPING_EXPOSURE_DEFAULT: 1.0
};

